[package]
name = "pattrick"
version = "0.3.6"
edition = "2021"
description = "Pattrick is a command line tool for managing Personal Access Tokens (PAT) in Azure DevOps."
repository = "https://github.com/jvanbuel/pattrick"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.10", features = ["derive", "cargo"] }
tokio = { version = "^1.34.0", features = ["macros"] }
azure_core = "^0.16"
azure_identity = "^0.16"
azure_svc_batch = "^0.16"
url = "2.4.1"
reqwest = "0.11.22"
serde = "1.0.192"
tabled = { version = "^0.14", features = ["color"] }
chrono = "0.4.31"
petname = "1.1.2"
netrc = "0.4.1"
dirs = "5.0.1"
pattrick-clap = { version = "^0.3.3", path = "pattrick-clap" }
openssl = { version = "^0.10.60", features = ["vendored"] }
owo-colors = "3.5.0"
base64 = "0.21.5"
self_update = { version = "0.39.0", features = [
    "archive-tar",
    "compression-flate2",
] }
async-recursion = "1.0.5"
log = "0.4.20"
serde_json = "1.0.108"
env_logger = "0.10.1"
strum_macros = "0.25.3"

[build-dependencies]
clap = { version = "4.4.10", features = ["derive"] }
clap_complete = "4.4.4"
clap_complete_fig = "4.4.2"
pattrick-clap = { version = "^0.3.3", path = "pattrick-clap" }

[workspace]
# This is a path relative to the workspace root.
members = ["pattrick-clap"]

[dev-dependencies]
tokio-test = "0.4.2"
