[package]
name = "pattrick"
version = "0.1.0"
edition = "2021"
description = "Pattrick is a command line tool for managing Personal Access Tokens (PAT) in Azure DevOps."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
tokio = { version = "1.0", features = ["macros"] }
azure_core = "0.1"
azure_identity = "0.1"
azure_svc_batch = "0.1"
url = "2.3.1"
reqwest = "0.11.12"
serde = "1.0.145"
tabled = "0.9.0"
emoji = "0.2.1"
chrono = "0.4.22"
petname = "1.1.2"
netrc = "0.4.1"
dirs = "4.0.0"
pattrick-clap = { path = "pattrick-clap" }
openssl = { version = "0.10.42", features = ["vendored"] }

[build-dependencies]
clap = { version = "4.0.9", features = ["derive"] }
clap_complete = "4.0.3"
clap_complete_fig = "4.0.1"
pattrick-clap = { path = "pattrick-clap" }

[workspace]
# This is a path relative to the workspace root.
members = ["pattrick-clap"]
