[package]
name = "pattrick"
version = "0.3.6"
edition = "2021"
description = "Pattrick is a command line tool for managing Personal Access Tokens (PAT) in Azure DevOps."
repository = "https://github.com/jvanbuel/pattrick"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive", "cargo"] }
tokio = { version = "^1.32.0", features = ["macros"] }
azure_core = "^0.13"
azure_identity = "^0.13"
azure_svc_batch = "^0.13"
url = "2.4.0"
reqwest = "0.11.18"
serde = "1.0.185"
tabled = { version = "^0.14", features = [ "color" ] }
chrono = "0.4.26"
petname = "1.1.2"
netrc = "0.4.1"
dirs = "5.0.1"
pattrick-clap = { version = "^0.3.3", path = "pattrick-clap" }
openssl = { version = "^0.10.56", features = ["vendored"] }
owo-colors = "3.5.0"
base64 = "0.21.3"
self_update = { version = "0.37.0", features = ["archive-tar", "compression-flate2"] }
async-recursion = "1.0.0"
log = "0.4.20"
serde_json = "1.0.105"
env_logger = "0.10.0"
strum_macros = "0.25.2"

[build-dependencies]
clap = { version = "4.3.23", features = ["derive"] }
clap_complete = "4.3.2"
clap_complete_fig = "4.3.1"
pattrick-clap = { version = "^0.3.3", path = "pattrick-clap" }

[workspace]
# This is a path relative to the workspace root.
members = ["pattrick-clap"]

[dev-dependencies]
tokio-test = "0.4.2"
