[package]
name = "pattrick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
tokio = { version = "1.0", features = ["macros"] }
azure_core = "0.1"
azure_identity = "0.1"
azure_svc_batch = "0.1"
url = "2.3.1"
reqwest = "0.11.12"
serde = "1.0.145"
tabled = "0.9.0"
emoji = "0.2.1"
chrono = "0.4.22"
petname = "1.1.2"
netrc = "0.4.1"
dirs = "4.0.0"
